x-openvpn-data: &openvpn-data
  volumes:
    - ./openvpn-data:/etc/openvpn
    - ./openvpn-config:/etc/openvpn-config

services:
  openvpn:
    image: ${OVPN_IMAGE:-szcq/openvpn:4.0.0-dev}
    container_name: openvpn
    restart: unless-stopped
    network_mode: host

    <<: *openvpn-data

    cap_add:
      - NET_ADMIN

    devices:
      - /dev/net/tun:/dev/net/tun

  openvpn-maintenance:
    image: ${OVPN_IMAGE:-szcq/openvpn:4.0.0-dev}
    restart: "no"
    network_mode: host

    environment:
      OVPN_MAINTENANCE: "true"

    <<: *openvpn-data

    profiles:
      - maintenance

    command:
      - state
      - doctor
    entrypoint:
      - /usr/local/bin/ovpn
