#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EN_README="$ROOT_DIR/README.md"
CN_README="$ROOT_DIR/README_CN.md"
COMPOSE_EXAMPLE="$ROOT_DIR/docker-compose.example.yaml"
ENV_EXAMPLE="$ROOT_DIR/.env.example"

for manual in "$EN_README" "$CN_README"; do
  test -s "$manual"
done

grep -Fq '## Client IP Management' "$EN_README"
grep -Fq 'data/client-ip.csv is the sole IP-assignment fact' "$EN_README"
grep -Fq 'ovpn client-ip apply' "$EN_README"
grep -Fq 'waiting for explicit application' "$EN_README"
grep -Fq 'ovpn network reconfigure' "$EN_README"
grep -Fq -- '--dry-run' "$EN_README"
grep -Fq -- '--yes' "$EN_README"
grep -Fq './openvpn-runtime/pool-persist.txt' "$EN_README"
grep -Fq '2^(32 - p) - 3' "$EN_README"
grep -Fq '10.42.0.0/24` provides 253 client' "$EN_README"
grep -Fq 'lowest unused address in the static region' "$EN_README"
grep -Fq "they do not need \`client-ip apply\` afterward" "$EN_README"
grep -Fq 'rejected before any registry, CCD, lease, or running configuration is' "$EN_README"

grep -Fq 'Runtime defaults apply only when the environment omits a value' "$EN_README"
grep -Fq 'requires a return route to the VPN CIDR through' "$EN_README"
grep -Fq 'ovpn client reissue laptop' "$EN_README"
grep -Fq "ovpn client release-ip laptop" "$EN_README"
grep -Fq 'complete pair of mount directories' "$EN_README"
grep -Fq "\`--dry-run\` only generates a read-only plan" "$EN_README"
grep -Fq "pull request targeting \`dev\`" "$EN_README"
grep -Fq 'host network namespace' "$EN_README"
grep -Fq '## 客户端 IP 管理' "$CN_README"
grep -Fq 'data/client-ip.csv 是唯一的 IP 分配事实源' "$CN_README"
grep -Fq 'ovpn client-ip apply' "$CN_README"
grep -Fq '等待显式应用' "$CN_README"
grep -Fq 'ovpn network reconfigure' "$CN_README"
grep -Fq './openvpn-runtime/pool-persist.txt' "$CN_README"
grep -Fq '2^(32-p)-3' "$CN_README"
grep -Fq '10.42.0.0/24` 可提供 253 个' "$CN_README"
grep -Fq '静态区内数值最小的空闲地址' "$CN_README"
grep -Fq '无需在其后再执行' "$CN_README"
grep -Fq '写入清单、CCD、租约或运行配置之前被拒绝' "$CN_README"
grep -Fq '运行时默认值只在环境未提供相应值时生效' "$CN_README"
grep -Fq '必须经 VPN 主机拥有到 VPN CIDR' "$CN_README"
grep -Fq "ovpn client release-ip laptop" "$CN_README"
grep -Fq 'ovpn client reissue laptop' "$CN_README"
grep -Fq '两个挂载目录整体' "$CN_README"
grep -Fq "\`--dry-run\` 只生成只读计划" "$CN_README"
grep -Fq "指向 \`dev\` 的 PR" "$CN_README"
grep -Fq '主机网络命名空间' "$CN_README"

grep -Fq './openvpn-runtime:/var/lib/openvpn' "$COMPOSE_EXAMPLE"
grep -Fq 'OVPN_TOPOLOGY=subnet' "$ENV_EXAMPLE"
grep -Fq 'OVPN_DYNAMIC_POOL_SIZE=64' "$ENV_EXAMPLE"

printf 'IPAM documentation smoke passed\n'
