package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/yjrszcq/openvpn-docker/internal/apperror"
)

type completionSpec struct {
	path    []string
	command command
}

type completionOption struct {
	long  string
	short string
}

func runCompletion(args []string, stdout, stderr io.Writer) int {
	if len(args) != 1 {
		return writeError(stderr, usageError("usage: ovpn completion (bash|zsh|fish)"))
	}
	var err error
	switch args[0] {
	case "bash":
		err = writeBashCompletion(stdout)
	case "zsh":
		err = writeZshCompletion(stdout)
	case "fish":
		err = writeFishCompletion(stdout)
	default:
		return writeError(stderr, usageError("unsupported shell "+args[0]+"; expected bash, zsh, or fish"))
	}
	if err != nil {
		return writeError(stderr, apperror.Wrap(apperror.ExitFailure, "output_failure", "write completion script", err))
	}
	return int(apperror.ExitSuccess)
}

func completionSpecs() []completionSpec {
	specs := make([]completionSpec, 0, 40)
	var walk func(command, []string)
	walk = func(current command, path []string) {
		specs = append(specs, completionSpec{path: append([]string(nil), path...), command: current})
		for _, child := range current.children {
			walk(child, append(path, child.name))
		}
	}
	walk(rootCommand, nil)
	return specs
}

func completionWords(spec completionSpec) []string {
	words := make([]string, 0, len(spec.command.children)+8)
	for _, child := range spec.command.children {
		words = append(words, child.name)
	}
	for _, option := range completionOptions(spec.command.usage) {
		if option.long != "" {
			words = append(words, option.long)
		}
		if option.short != "" {
			words = append(words, option.short)
		}
	}
	words = append(words, "--help", "-h")
	if len(spec.path) == 0 {
		words = append(words, "--version", "-V", "-v")
	}
	return uniqueWords(words)
}

func completionOptions(usage string) []completionOption {
	byLong := make(map[string]*completionOption)
	order := make([]string, 0, 8)
	for _, field := range strings.Fields(usage) {
		field = strings.Trim(field, "[]()")
		var current *completionOption
		for _, value := range strings.Split(field, "|") {
			value = strings.Trim(value, "[](),")
			if !strings.HasPrefix(value, "-") || value == "-" {
				continue
			}
			if strings.HasPrefix(value, "--") {
				option, found := byLong[value]
				if !found {
					option = &completionOption{long: value}
					byLong[value] = option
					order = append(order, value)
				}
				current = option
				continue
			}
			if len(value) == 2 && current != nil {
				current.short = value
			}
		}
	}
	options := make([]completionOption, 0, len(order))
	for _, name := range order {
		options = append(options, *byLong[name])
	}
	return options
}

func uniqueWords(values []string) []string {
	seen := make(map[string]struct{}, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		if _, found := seen[value]; found {
			continue
		}
		seen[value] = struct{}{}
		result = append(result, value)
	}
	return result
}

func sortedCompletionSpecs() []completionSpec {
	specs := completionSpecs()
	sort.SliceStable(specs, func(left, right int) bool {
		return len(specs[left].path) > len(specs[right].path)
	})
	return specs
}

func writePathCases(writer io.Writer, wordExpression string) error {
	if _, err := fmt.Fprintf(writer, "  local joined=\" %s \"\n  case \"$joined\" in\n", wordExpression); err != nil {
		return err
	}
	for _, spec := range sortedCompletionSpecs() {
		if len(spec.path) == 0 {
			continue
		}
		path := strings.Join(spec.path, " ")
		if _, err := fmt.Fprintf(writer, "    ' %s '*) key='%s' ;;\n", path, path); err != nil {
			return err
		}
	}
	_, err := io.WriteString(writer, "    *) key='' ;;\n  esac\n")
	return err
}

func writeCandidateCases(writer io.Writer, assignment func([]string) string) error {
	if _, err := io.WriteString(writer, "  case \"$key\" in\n"); err != nil {
		return err
	}
	for _, spec := range completionSpecs() {
		path := strings.Join(spec.path, " ")
		if _, err := fmt.Fprintf(writer, "    '%s') candidates=%s ;;\n", path, assignment(completionWords(spec))); err != nil {
			return err
		}
	}
	_, err := io.WriteString(writer, "  esac\n")
	return err
}

func writeBashCompletion(writer io.Writer) error {
	if _, err := io.WriteString(writer, `# bash completion for ovpn; generated by "ovpn completion bash"
_ovpn_completion() {
  local cur prev key candidates
  COMPREPLY=()
  cur="${COMP_WORDS[COMP_CWORD]}"
  prev="${COMP_WORDS[COMP_CWORD-1]}"
`); err != nil {
		return err
	}
	if err := writePathCases(writer, "${COMP_WORDS[*]:1:COMP_CWORD-1}"); err != nil {
		return err
	}
	if _, err := io.WriteString(writer, `  case "$prev" in
    --name|-n) candidates="$(ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $2}')" ;;
    --id|-i) candidates="$(ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $1}')" ;;
    --ipv4|-4) candidates='auto dynamic' ;;
    --lines|-l) candidates='0 50 100 200' ;;
    *)
`); err != nil {
		return err
	}
	if err := writeCandidateCases(writer, func(words []string) string { return "'" + strings.Join(words, " ") + "'" }); err != nil {
		return err
	}
	_, err := io.WriteString(writer, `      ;;
  esac
  COMPREPLY=( $(compgen -W "$candidates" -- "$cur") )
}
complete -F _ovpn_completion ovpn
`)
	return err
}

func writeZshCompletion(writer io.Writer) error {
	if _, err := io.WriteString(writer, `#compdef ovpn
# zsh completion for ovpn; generated by "ovpn completion zsh"
_ovpn() {
  local cur prev key joined
  local -a candidates
  cur="${words[CURRENT]}"
  prev="${words[CURRENT-1]}"
`); err != nil {
		return err
	}
	if err := writePathCases(writer, "${(j: :)words[2,CURRENT-1]}"); err != nil {
		return err
	}
	if _, err := io.WriteString(writer, `  case "$prev" in
    --name|-n) candidates=(${(f)"$(ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $2}')"}) ;;
    --id|-i) candidates=(${(f)"$(ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $1}')"}) ;;
    --ipv4|-4) candidates=(auto dynamic) ;;
    --lines|-l) candidates=(0 50 100 200) ;;
    *)
`); err != nil {
		return err
	}
	if err := writeCandidateCases(writer, func(words []string) string {
		quoted := make([]string, 0, len(words))
		for _, word := range words {
			quoted = append(quoted, "'"+word+"'")
		}
		return "(" + strings.Join(quoted, " ") + ")"
	}); err != nil {
		return err
	}
	_, err := io.WriteString(writer, `      ;;
  esac
  compadd -Q -- $candidates
}
compdef _ovpn ovpn
`)
	return err
}

func writeFishCompletion(writer io.Writer) error {
	if _, err := io.WriteString(writer, `# fish completion for ovpn; generated by "ovpn completion fish"
function __ovpn_path_is
    set -l tokens (commandline -opc)
    set -e tokens[1]
    for expected in $argv
        if test (count $tokens) -eq 0; or test "$tokens[1]" != "$expected"
            return 1
        end
        set -e tokens[1]
    end
    return 0
end

function __ovpn_client_names
    ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $2}'
end

function __ovpn_client_ids
    ovpn client list --full-id 2>/dev/null | awk 'NR > 1 {print $1}'
end

complete -c ovpn -f
complete -c ovpn -n '__fish_use_subcommand' -s v -d 'print short version'
complete -c ovpn -n '__fish_use_subcommand' -s V -l version -d 'print full version report'
`); err != nil {
		return err
	}
	for _, spec := range completionSpecs() {
		path := strings.Join(spec.path, " ")
		if len(spec.command.children) > 0 {
			condition := "__fish_use_subcommand"
			if path != "" {
				names := make([]string, 0, len(spec.command.children))
				for _, child := range spec.command.children {
					names = append(names, child.name)
				}
				condition = "__ovpn_path_is " + path + "; and not __fish_seen_subcommand_from " + strings.Join(names, " ")
			}
			for _, child := range spec.command.children {
				if _, err := fmt.Fprintf(writer, "complete -c ovpn -n '%s' -a '%s' -d '%s'\n", condition, child.name, fishSingleQuote(child.summary)); err != nil {
					return err
				}
			}
		}
		if path == "" {
			continue
		}
		condition := "__ovpn_path_is " + path
		for _, option := range completionOptions(spec.command.usage) {
			parts := []string{"complete -c ovpn -n '" + condition + "'"}
			if option.short != "" {
				parts = append(parts, "-s "+strings.TrimPrefix(option.short, "-"))
			}
			parts = append(parts, "-l "+strings.TrimPrefix(option.long, "--"))
			switch option.long {
			case "--name":
				parts = append(parts, "-r -f -a '(__ovpn_client_names)'")
			case "--id":
				parts = append(parts, "-r -f -a '(__ovpn_client_ids)'")
			case "--ipv4":
				parts = append(parts, "-f -a 'auto dynamic'")
			case "--lines":
				parts = append(parts, "-r -f -a '0 50 100 200'")
			case "--output":
				parts = append(parts, "-r -F")
			}
			if _, err := fmt.Fprintln(writer, strings.Join(parts, " ")); err != nil {
				return err
			}
		}
	}
	_, err := io.WriteString(writer, "complete -c ovpn -s h -l help -d 'show command help'\n")
	return err
}

func fishSingleQuote(value string) string {
	return strings.ReplaceAll(value, "'", "\\'")
}
